### ISSUE TITLE
Don't update when nothing has changed

### ISSUE THREAD

**Issue by edalzell** [edalzell/statamic-profiler#7]
I'm stumped. I can get a select field's current value into the label, but I can't quite figure out how to get that current value to be the one showing/already-selected in the active portion of a <select><option><option>... pop-up list. The idea being, if the page is presented as-is, and the user does nothing except tap "Update" (without having made any changes), nothing should change! Again, is an example of that too much to include in your ReadMe? It would sure be useful to me!

**Comment by edalzell** [comment]
I'm not sure what you mean @iDGS. Can you provide a better example?

**Comment by iDGS** [comment]
Again, sorry: above I conflated two separate issues. I've since figured out how to get the select field to show the currently selected value. Obviously 🤦‍♂️ by conditionally inserting the `selected` attribute. E.g., 
```
<select
              name="mentoring_availability"
                id="mentoring_availability"
     ><option value="yep" {{ if (old:mentoring_availability == 'yep') or (mentoring_availability == 'yep') }}selected{{
            /if }}>yep</option
     ><option value="maybe" {{ if (old:mentoring_availability == 'maybe') or (mentoring_availability == 'maybe') }}selected{{
            /if }}>maybe</option
     ><option value="nope" {{ if (old:mentoring_availability == 'nope') or (mentoring_availability == 'nope') }}selected{{
            /if }}>nope</option
     ><option value="never" {{ if (old:mentoring_availability == 'never') or (mentoring_availability == 'never') }}selected{{
            /if }}>never</option></select>
```
(Sidebar: "Yep" instead of "Yes" and "Nope" instead of "No" because php seemed to think "yes" always means "true" and "no" means "", even in my YAML front matter fields. But NVM all that.) 


To the real issue at hand...

YMMV, but I've found that the add-on (v1.2/current) will alter fields that are not even referenced in the `{{ user_profile:edit_form }}` E.g., without making any edits whatsoever, but just hitting "Update" button this field in the front matter
```
-note_by_admin_to_member: This is a test to see if the Admin can leave you a special for-your-eyes-only note that you will see when you log in!
```
was changed to:
```
+note_by_admin_to_member: >
+  This is a test to see if the Admin can leave you a special for-your-eyes-only note that you will see
+  when you log in!
```
(the above to samples copy/pasted from a `git diff HEAD (file path/filename)` result.)

I recognize they're *functionally* the same. I was just surprised because, again, the field got reformatted even though it quote/unquote didn't need it, and was in any case not referenced in the `{{ user_profile:edit_form }}`.

So I guess that's two issues again. 1) unreferenced field being changed, 2) (unnecessary--debatable, I know) reformatting being applied when no edit was made. 

Sorry if this is an overreaction. When Git reports something is changed, and I didn't think it should have been, I went digging and this is simply what I found.

**Comment by edalzell** [comment]
That's just the YAML parser saving it two different ways. I have no control over that.

As the end result is the same (no "real" data changed), I'm going to close this.
